--- LOCALES: enUS
--- Локаль по-умолчанию.
--- Если нет подходящей локали из настроек игры -  будет использоваться именно она

TARGETCHARMS_TITLE = "TargetCharms";

TARGETCHARMS_OPTIONS_ENABLE = "Enabled";
TARGETCHARMS_OPTIONS_PARTYONLY = "Show only in Party/Raid";
TARGETCHARMS_OPTIONS_TITLE = "TargetCharms";
TARGETCHARMS_OPTIONS_LAYOUT_TEXT = "Custom Layout";
TARGETCHARMS_OPTIONS_DRAG = "Draggable";
TARGETCHARMS_OPTIONS_SHOWONTARGET = "Show only while Targeting";
TARGETCHARMS_OPTIONS_TOGGLEICON = "Togglable Buttons";
TARGETCHARMS_OPTIONS_SHOWICONS = "Show Icons";
TARGETCHARMS_OPTIONS_SCALE = "Scale";
TARGETCHARMS_OPTIONS_OPACITY = "Opacity";
TARGETCHARMS_OPTIONS_XSPACING = "X Spacing";
TARGETCHARMS_OPTIONS_YSPACING = "Y Spacing";
TARGETCHARMS_OPTIONS_SHOW_TITLE = "Display:";
TARGETCHARMS_OPTIONS_CLOSE_BUTTON = "Close";
TARGETCHARMS_OPTIONS_MAIN_PROFILE = "Set As Main Profile To Copy"
TARGETCHARMS_OPTIONS_COPY_BUTTON = "Copy Settings From";
TARGETCHARMS_OPTIONS_SOURCE = "Source:";
TARGETCHARMS_OPTIONS_COPY_SETTINGS = "Copy Settings";
TARGETCHARMS_OPTIONS_PRESETS_TITLE = "Preset Layouts";
TARGETCHARMS_OPTIONS_CUSTOM_LAYOUT = "Custom";
TARGETCHARMS_OPTIONS_READYCHECK_TITLE = "Ready Button";
TARGETCHARMS_OPTIONS_READYCHECK_TEXT = "Text";
TARGETCHARMS_OPTIONS_FLARE_TITLE = "World Markers";
TARGETCHARMS_OPTIONS_WIDTH = "Width";
TARGETCHARMS_OPTIONS_PROFILE = "Profile";
TARGETCHARMS_PANEL_SHOW = "Show Setup";
TARGETCHARMS_READYCHECK_TEXT = "Ready?";
TARGETCHARMS_MSG_TAG = "TargetCharms: ";
TARGETCHARMS_CMD_HELP = "/TargetCharms [Reset|Setup]";
TARGETCHARMS_SLASH1 = "/targetcharms";
TARGETCHARMS_SLASH2 = "/tc";
TARGETCHARMS_LOADED = "Loaded";
TARGETCHARMS_ERROR_INVALIDCHAR = "Invalid Position Character";
TARGETCHARMS_OPTIONS_RESET = "Position and Values Reset";

--Positions & Charms
TARGETCHARMS_POSITION_UP = "^";
TARGETCHARMS_POSITION_DOWN = "v";
TARGETCHARMS_POSITION_LEFT = "<";
TARGETCHARMS_POSITION_RIGHT = ">";
TARGETCHARMS_CHARM1 = "1";
TARGETCHARMS_CHARM2 = "2";
TARGETCHARMS_CHARM3 = "3";
TARGETCHARMS_CHARM4 = "4";
TARGETCHARMS_CHARM5 = "5";
TARGETCHARMS_CHARM6 = "6";
TARGETCHARMS_CHARM7 = "7";
TARGETCHARMS_CHARM8 = "8";
TARGETCHARMS_CHARM9 = "9"; --Not currently used
TARGETCHARMS_CHARM0 = "0";

TARGETCHARMS_BLUEFLARE = "B";
TARGETCHARMS_GREENFLARE = "G";
TARGETCHARMS_PURPLEFLARE = "P";
TARGETCHARMS_REDFLARE = "R";
TARGETCHARMS_YELLOWFLARE = "Y";
TARGETCHARMS_WHITEFLARE = "W";
TARGETCHARMS_SILVERFLARE = "S";
TARGETCHARMS_ORANGEFLARE = "O";
TARGETCHARMS_DRAG = "D";
TARGETCHARMS_CLEARFLARE = "X";

--Lower case on CMDs
TargetCharms_CMDS = { "reset", "setup" };
